title: Quantum Data
email: quantumudit@gmail.com
description: Data Analytics Blog Posts
author: Udit Kumar Chatterjee
baseurl: ""
url: "https://quantumudit.github.io"

# Social Profiles
twitter_username: quantumudit
github_username: quantumudit
facebook_username:
instagram_username:
linkedin_username: uditkumarchatterjee

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
